In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('./data/multi.csv')
df.head()

,pnu,x,y,count,yyyymmdd,area,price,withoutRent,deposit,rent,builtyear,시군구,번지,도로조건,전월세구분,도로명,군,구
0,1111010100,953138.7,1954566.0,492,20110120,33.00,6000,1,6000,0,1996.0,서울특별시 종로구 청운동,8*,-,전세,자하문로30길,종로구,청운동
1,1111010100,953161.6,1954552.0,492,20110126,146.32,30000,1,30000,0,2000.0,서울특별시 종로구 청운동,1**,-,전세,자하문로,종로구,청운동
2,1111010100,953159.9,1954537.9,492,20110209,39.70,9897,0,5000,40,1995.0,서울특별시 종로구 청운동,1**,-,월세,자하문로,종로구,청운동
3,1111010100,953129.8,1954559.4,492,20110222,75.99,20000,1,20000,0,1993.0,서울특별시 종로구 청운동,1**,-,전세,자하문로28길,종로구,청운동
4,1111010100,953141.0,1954561.1,492,20110302,39.00,7724,0,6500,10,1995.0,서울특별시 종로구 청운동,1**,25m이상,월세,자하문로,종로구,청운동

In [9]:
df['yyyymmdd'] = pd.to_datetime(df['yyyymmdd'], format="%Y%m%d")

In [11]:
df['year'] = df['yyyymmdd'].dt.year
df['quarter'] = df['yyyymmdd'].dt.quarter

In [15]:
df.sort_values(ascending=True, by='yyyymmdd', inplace=True)

In [17]:
df.reset_index(drop=True, inplace=True)

In [18]:
df.to_csv('./data/home.csv', index=False)